name: Testing
on:
    push: 
          branches: [main]
    pull_request:
          branches: [main]
    workflow_call:
        secrets:
          DATABASE_PASSWORD:
            required: true
jobs:
    test:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:15
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
              POSTGRES_DB: hackathon_test_db
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        env:
          DATABASE_NAME: hackathon_test_db
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        steps:
          - name: checkout repo
            uses: actions/checkout@v4
          - name: setup python
            uses: actions/setup-python@v5
            with:
              python-version: "3.13"
          - name: install uv
            run: pip install uv
          - name: install dependencies
            run: uv sync
          - name: run tests
            run: uv run pytest tests/
