name: Deployment
on:
  push:
      branches: [main]
jobs:
    testing:
      uses: ./.github/workflows/ci.yml
    deployment:
      needs: testing
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: deploy
          run: echo "Deploying to production..."
      
